### ISSUE TITLE
ask some update problems about EMAN2

### ISSUE THREAD

**Issue by lqhuang** [cryoem/eman2#1]
Hi, I'm a graduate student for biophysics.
I'm studying Single Particle Analysis recently, and I find EMAN2.
It's a wonderful software and helps me a lot. Thanks for your work!

Though I know it's a matter to solve dependencies problem of old codes. I still want to ask that do you have a plan or schedule to update EMAN2 from python2 to python3?

Anyway, best wishes! :)

**Comment by thevernonator** [comment]
Thursday, May 26, 2016, 2:57am

Converting from Python 2 to 3 is one of several ongoing efforts we  
have going.
It will not be done immediately, but hopefully well before the end of  
the year.

**Comment by lqhuang** [comment]
Thank you for your answer!
