### ISSUE TITLE
Could NOT find OpenGL

### ISSUE THREAD

**Issue by shguan10** [cryoem/eman2#175]
I was following the instructions on the EMAN wiki to build from source, but I'm stuck at the cmake step. Here is the error output:

### BEGIN ### CHECK_REQUIRED_LIB HDF5 hdf5 hdf5.h  
HDF5_INCLUDE_PATH: /home/xguan/anaconda2/envs/eman-env/include
HDF5_LIBRARY: /home/xguan/anaconda2/envs/eman-env/lib/libhdf5.so
Searching in /home/xguan/anaconda2/envs/eman-env/include for hdf5.h and  ...
FIND_LIBRARY: HDF5_LIBRARY NAMES hdf5  PATHS /lib /home/xguan/anaconda2/envs/eman-env/lib
### END ### CHECK_REQUIRED_LIB HDF5 hdf5 hdf5.h  
HDF5_INCLUDE_PATH: /home/xguan/anaconda2/envs/eman-env/include
HDF5_LIBRARY: /home/xguan/anaconda2/envs/eman-env/lib/libhdf5.so
HDF5_LIBRARY: /home/xguan/anaconda2/envs/eman-env/lib/libhdf5.so
PNG_LIBRARIES: /home/xguan/anaconda2/envs/eman-env/lib/libpng.so;/home/xguan/anaconda2/envs/eman-env/lib/libz.so
CMake Error at /home/xguan/anaconda2/envs/eman-env/share/cmake-3.8/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find OpenGL (missing: OPENGL_gl_LIBRARY OPENGL_INCLUDE_DIR)
Call Stack (most recent call first):
  /home/xguan/anaconda2/envs/eman-env/share/cmake-3.8/Modules/FindPackageHandleStandardArgs.cmake:377 (_FPHSA_FAILURE_MESSAGE)
  /home/xguan/anaconda2/envs/eman-env/share/cmake-3.8/Modules/FindOpenGL.cmake:170 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  cmake/OpenGL.cmake:1 (find_package)
  libEM/CMakeLists.txt:175 (include)

Thanks for your help!

**Comment by shadowwalkersb** [comment]
Can you provide the output for the following commands while `eman-env` is activated?
```
e2version.py
conda info -a
conda list
```

**Comment by shguan10** [comment]
Thank you for responding!
---
output for `e2version.py`
EMAN 2.2 (GITHUB: 2018-01-27 21:11 - commit: c96871b )
Your EMAN2 is running on: Linux-4.10.0-28-generic-x86_64-with-debian-stretch-sid 4.10.0-28-generic
Your Python version is: 2.7.13
---
output for `conda info -a`
     active environment : None
       user config file : /home/xinyu/.condarc
 populated config files : 
          conda version : 4.4.8
    conda-build version : 3.0.19
         python version : 2.7.13.final.0
       base environment : /home/xinyu/EMAN2  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
          package cache : /home/xinyu/EMAN2/pkgs
                          /home/xinyu/.conda/pkgs
       envs directories : /home/xinyu/EMAN2/envs
                          /home/xinyu/.conda/envs
               platform : linux-64
             user-agent : conda/4.4.8 requests/2.14.2 CPython/2.7.13 Linux/4.10.0-28-generic ubuntu/16.04 glibc/2.23
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

# conda environments:
#
base                  *  /home/xinyu/EMAN2

sys.version: 2.7.13 |Continuum Analytics, Inc.| (defa...
sys.prefix: /home/xinyu/EMAN2
sys.executable: /home/xinyu/EMAN2/bin/python
conda location: /home/xinyu/EMAN2/lib/python2.7/site-packages/conda
conda-build: /home/xinyu/EMAN2/bin/conda-build
conda-convert: /home/xinyu/EMAN2/bin/conda-convert
conda-develop: /home/xinyu/EMAN2/bin/conda-develop
conda-env: /home/xinyu/EMAN2/bin/conda-env
conda-index: /home/xinyu/EMAN2/bin/conda-index
conda-inspect: /home/xinyu/EMAN2/bin/conda-inspect
conda-metapackage: /home/xinyu/EMAN2/bin/conda-metapackage
conda-render: /home/xinyu/EMAN2/bin/conda-render
conda-skeleton: /home/xinyu/EMAN2/bin/conda-skeleton
conda-verify: /home/xinyu/EMAN2/bin/conda-verify
user site dirs: 

CIO_TEST: <not set>
CONDA_ROOT: /home/xinyu/EMAN2
DEFAULTS_PATH: /usr/share/gconf/ubuntu.default.path
MANDATORY_PATH: /usr/share/gconf/ubuntu.mandatory.path
PATH: /home/xinyu/EMAN2/bin:/usr/local/MATLAB/R2017b/bin:/home/xinyu/.bin:/home/xinyu/bin:/home/xinyu/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
REQUESTS_CA_BUNDLE: <not set>
SSL_CERT_FILE: <not set>
XDG_SEAT_PATH: /org/freedesktop/DisplayManager/Seat0
XDG_SESSION_PATH: /org/freedesktop/DisplayManager/Session0


WARNING: could not import _license.show_info
# try:
# $ conda install -n root _license
---
output for `conda list`
# packages in environment at /home/xinyu/EMAN2:
#
# Name                    Version                   Build  Channel
absl-py                   0.1.9                     <pip>
argparse                  1.2.1                    py27_0    auto
asn1crypto                0.22.0                   py27_0  
backports                 1.0                      py27_0  
backports.weakref         1.0.post1                 <pip>
beautifulsoup4            4.6.0                    py27_0  
bleach                    1.5.0                     <pip>
boost                     1.63.0                   py27_5    conda-forge
boost-cpp                 1.63.0                        2    conda-forge
bsddb                     1.0                      py27_1  
bzip2                     1.0.6                         3  
cairo                     1.12.18                       6  
catkin_pkg                0.1.26                   py27_0    auto
certifi                   2016.2.28                py27_0  
cffi                      1.10.0                   py27_0  
chardet                   3.0.4                    py27_0  
conda                     4.4.8                    py27_0  
conda-build               3.0.19           py27h652c75d_0  
conda-env                 2.6.0                h36134e3_1  
conda-verify              2.0.0                    py27_0  
contextlib2               0.5.5                    py27_0  
cryptography              1.8.1                    py27_0  
db                        5.3.28                        1  
decorator                 4.1.2                    py27_0  
docutils                  0.14             py27hae222c1_0  
eman2                     2.2                  np19py27_0    file:///home/eman2/anaconda2/conda-bld
enum34                    1.1.6                    py27_0  
fftw-mpi                  3.3.6                         2    cryoem
filelock                  2.0.7                    py27_0  
fontconfig                2.11.1                        6  
freetype                  2.5.5                         1  
ftgl                      2.1.3                         1    cryoem
funcsigs                  1.0.2                     <pip>
futures                   3.1.1                    py27_0  
get_terminal_size         1.0.0                    py27_0  
glob2                     0.5                      py27_0  
gsl                       2.2.1                         0  
hdf5                      1.8.18               h6792536_1    anaconda
html5lib                  0.9999999                 <pip>
icu                       58.2                 h9c2bf20_1    anaconda
idna                      2.6                      py27_0  
intel-openmp              2018.0.0             hc7b2577_8    anaconda
ipaddress                 1.0.18                   py27_0  
ipython                   5.3.0                    py27_0  
ipython_genutils          0.2.0                    py27_0  
jinja2                    2.9.6                    py27_0  
jpeg                      9b                            0  
Keras                     2.1.3                     <pip>
libffi                    3.2.1                         1  
libgcc                    5.2.0                         0  
libgcc-ng                 7.2.0                h7cc24e2_2    anaconda
libgfortran               1.0                           0  
libgfortran-ng            7.2.0                h9f7466a_2    anaconda
libgpuarray               0.6.9                         0  
libiconv                  1.14                          0  
libpng                    1.6.17                        0  
libstdcxx-ng              7.2.0                h7a57d05_2    anaconda
libtiff                   4.0.9                h28f6b97_0    anaconda
libxml2                   2.9.4                         0  
mako                      1.0.6                    py27_0  
Markdown                  2.6.11                    <pip>
markupsafe                1.0                      py27_0  
matplotlib                1.4.3                np19py27_2  
mkl                       2018.0.1             h19d6760_4    anaconda
mkl-service               1.1.2                    py27_3  
mock                      2.0.0                     <pip>
nose                      1.3.7                    py27_1  
numpy                     1.9.3                    py27_0  
numpy                     1.14.0                    <pip>
openblas                  0.2.14                        3  
openmpi                   2.0.2                         0    cryoem
openssl                   1.0.2l                        0  
packaging                 16.8                     py27_0  
patchelf                  0.9                           0  
path.py                   10.3.1                   py27_0  
pathlib2                  2.3.0                    py27_0  
pbr                       3.1.1                     <pip>
pexpect                   4.2.1                    py27_0  
pickleshare               0.7.4                    py27_0  
pip                       9.0.1                    py27_1  
pixman                    0.32.6                        0  
pkginfo                   1.4.1                    py27_0  
prompt_toolkit            1.0.15                   py27_0  
protobuf                  3.5.1                     <pip>
ptyprocess                0.5.2                    py27_0  
py2cairo                  1.10.0                   py27_2  
pycosat                   0.6.3            py27ha4109ae_0  
pycparser                 2.18                     py27_0  
pydusa                    1.15                     np19_9    cryoem
pygments                  2.2.0                    py27_0  
pygpu                     0.6.9                    py27_0  
pyopengl                  3.1.0                    py27_0    conda-forge
pyopenssl                 17.0.0                   py27_0  
pyparsing                 2.0.3                    py27_0  
pypng                     0.0.18                    <pip>
pyqt                      4.11.4                   py27_4  
python                    2.7.13                        0  
python-dateutil           2.6.1                    py27_0  
pytz                      2017.2                   py27_0  
pyyaml                    3.12                     py27_0  
qt                        4.8.7                         3  
readline                  6.2                           2  
requests                  2.14.2                   py27_0  
ruamel_yaml               0.11.14                  py27_1  
scandir                   1.5                      py27_0  
scikit-learn              0.19.1           py27h445a80a_0    anaconda
scipy                     1.0.0            py27hf5f0f52_0    anaconda
setuptools                36.4.0                   py27_1  
simplegeneric             0.8.1                    py27_1  
sip                       4.18                     py27_0  
six                       1.10.0                   py27_0  
sqlite                    3.13.0                        0  
tensorflow                1.5.0                     <pip>
tensorflow-gpu            1.5.0                     <pip>
tensorflow-tensorboard    1.5.0                     <pip>
theano                    0.9.0                    py27_0  
tk                        8.5.18                        0  
traitlets                 4.3.2                    py27_0  
wcwidth                   0.1.7                    py27_0  
Werkzeug                  0.14.1                    <pip>
wheel                     0.29.0                   py27_0  
xz                        5.2.3                         0  
yaml                      0.1.6                         0  
zlib                      1.2.11                        0

**Comment by sludtke42** [comment]
Hi, since Tunay had replied, I didn't look at this carefully until now. The message seems clear:

> Could NOT find OpenGL (missing: OPENGL_gl_LIBRARY OPENGL_INCLUDE_DIR)
> 

OpenGL is not a supplied dependency in Anaconda, it is part of the operating system/driver infrastructure. Most people will have Nvidia graphics cards on their computers, and will then install the proprietary Nvidia drivers, which includes OpenGL. If you have some other graphics card, you'd normally install Mesa.  Anyway, the complaint you're getting is that it can't find OpenGL.


--------------------------------------------------------------------------------------
Steven Ludtke, Ph.D.
Charles C. Bell Jr., Professor of Structural Biology
Dept. of Biochemistry and Molecular Biology                      (www.bcm.edu/biochem <http://www.bcm.edu/biochem>)
Co-Director CIBR Center                                    (www.bcm.edu/research/cibr <http://www.bcm.edu/research/cibr>)
Co-Director National Center For Macromolecular Imaging                  (ncmi.bcm.edu <http://ncmi.bcm.edu/>)
Baylor College of Medicine                             
sludtke@bcm.edu <mailto:sludtke@bcm.edu>

**Comment by shguan10** [comment]
Thanks for your response! 

It turns out that my computer was lacking a graphics card. That's why I was missing OpenGL.

**Comment by sludtke42** [comment]
Ok. You can still install Mesa, even without a dedicated GPU. Performance isn't really an issue.
--------------------------------------------------------------------------------------
Steven Ludtke, Ph.D.
Charles C. Bell Jr., Professor of Structural Biology
Dept. of Biochemistry and Molecular Biology                      (www.bcm.edu/biochem)
Co-Director CIBR Center                                    (www.bcm.edu/research/cibr)
Co-Director National Center For Macromolecular Imaging                  (ncmi.bcm.edu)
Baylor College of Medicine                             
sludtke@bcm.edu
