### ISSUE TITLE
No module named past.utils

### ISSUE THREAD

**Issue by Arunabhathreya** [cryoem/eman2#228]
Upon installing Eman2 on Ubuntu16.04, when I tried running e2projectmanager.py, this came up:

`(eman-env) root@thlab:~/.conda/envs/eman-env/bin# e2projectmanager.py 
Traceback (most recent call last):
  File "/home/thlab/.conda/envs/eman-env/bin/e2projectmanager.py", line 35, in <module>
    from past.utils import old_div
ImportError: No module named past.utils
`
Future is already installed using pip.
![pip_install_future](https://user-images.githubusercontent.com/41703026/43222041-7baf728a-906c-11e8-8062-0075b7dc9142.png)
![past_utils](https://user-images.githubusercontent.com/41703026/43222042-7bdbb9b2-906c-11e8-9ccf-5f59c1766c6a.png)

**Comment by sludtke42** [comment]
What version are you using?
(e2version.py)

try 
conda install future
--------------------------------------------------------------------------------------
Steven Ludtke, Ph.D. <sludtke@bcm.edu <mailto:sludtke@bcm.edu>>                      Baylor College of Medicine 
Charles C. Bell Jr., Professor of Structural Biology
Dept. of Biochemistry and Molecular Biology                      (www.bcm.edu/biochem <http://www.bcm.edu/biochem>)
Academic Director, CryoEM Core                                        (cryoem.bcm.edu <http://cryoem.bcm.edu/>)
Co-Director CIBR Center                                    (www.bcm.edu/research/cibr <http://www.bcm.edu/research/cibr>)
Co-Director National Center For Macromolecular Imaging                  (ncmi.bcm.edu <http://ncmi.bcm.edu/>)
