### ISSUE TITLE
GUI: text field too small in e2projectmanager

### ISSUE THREAD

**Issue by rsrock** [cryoem/eman2#284]
In e2projectmanager, we cannot run e2initialmodel.py jobs because the "symmetry number" field is too small to enter a valid number (it's only a few pixels wide).  As a workaround, we have been running e2initialmodel.py in the shell. 

This is on:
```
EMAN 2.22 final (GITHUB: 2018-08-20 20:33 - commit: f4f3952 )
Your EMAN2 is running on: Mac OS 10.14.1 x86_64
Your Python version is: 2.7.14
```

**Comment by sludtke42** [comment]
Thanks for mentioning this. I hadn't noticed it before. You can actually still type a number in the box, and it works properly. You can also go to the 'command' tab and enter the symmetry there, which has the same effect, but we will update the GUI so this doesn't happen in future.
cheers

--------------------------------------------------------------------------------------
Steven Ludtke, Ph.D. <sludtke@bcm.edu>                      Baylor College of Medicine 
Charles C. Bell Jr., Professor of Structural Biology
Dept. of Biochemistry and Molecular Biology                      (www.bcm.edu/biochem)
Academic Director, CryoEM Core                                        (cryoem.bcm.edu)
Co-Director CIBR Center                                    (www.bcm.edu/research/cibr)

**Comment by shadowwalkersb** [comment]
@rsrock , can this issue be closed?
