### ISSUE TITLE
ImportError: No module named global_def

### ISSUE THREAD

**Issue by lisaeshunwilson** [cryoem/eman2#360]
When I run this code on my local HPC cluster, I receive this error when running the refine.py script for multi-reference refinement: 

```
Traceback (most recent call last):
  File "/opt/qb3/eman2-2.05/contrib/nogales/refine.py", line 35, in <module>
    import global_def
ImportError: No module named global_def
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
```

**Comment by sludtke42** [comment]
Hi Lisa,
this is a 7+ year old version of EMAN2, and predates the change away from BDB (in EMAN2.1) and the new compilation/distribution system (in EMAN2.2). We also know nothing about how EMAN2 was configured on your cluster (I assume based on the 'job' comment that this is a cluster?).   It looks like the binary you get when you run 'python' may not be the same as the python interpreter used when EMAN2 was compiled/installed. It could also be an issue with your PYTHONPATH.   If someone else there has an account where this version of EMAN2 works, you might try comparing your PATH and PYTHONPATH (no longer used in EMAN2.2, but was used in 2.05) to theirs to look for differences. You may need to consult with your local sysadmin who should know more about how this was configured on your machine.

--------------------------------------------------------------------------------------
Steven Ludtke, Ph.D. <sludtke@bcm.edu <mailto:sludtke@bcm.edu>>                      Baylor College of Medicine 
Charles C. Bell Jr., Professor of Structural Biology
Dept. of Biochemistry and Molecular Biology                      (www.bcm.edu/biochem <http://www.bcm.edu/biochem>)
Academic Director, CryoEM Core                                        (cryoem.bcm.edu <http://cryoem.bcm.edu/>)
Co-Director CIBR Center                                    (www.bcm.edu/research/cibr <http://www.bcm.edu/research/cibr>)

**Comment by lisaeshunwilson** [comment]
Hi Dr. Ludtke! 

Thank you so much for your very helpful response, I will work on using the most updated version of EMAN2 (2.2 instead of 2.05) and addressing the concerns you bring up. I will let you know how it goes! 

Thank you so much again! 

Lisa

**Comment by shadowwalkersb** [comment]
@lisaeshunwilson , can we close this issue?

**Comment by lisaeshunwilson** [comment]
Yes! Sorry! 

Lisa Eshun-Wilson | Nogales Lab | UC Berkeley
