### ISSUE TITLE
If EMAN2 isn't working for MAC, do this!

### ISSUE THREAD

**Issue by josharnoldjosh** [cryoem/eman2#388]
First, follow the install instructions: https://blake.bcm.edu/emanwiki/EMAN2/Install/BinaryInstallAnaconda/2.22

Then, open terminal, and run `open ~/.bash_profile`

Add to that file `export PATH="/Users/yourusername/EMAN2/bin:$PATH"`

Save, and restart your terminal, then see if it works.

**Comment by shadowwalkersb** [comment]
I believe the wiki instructions and installer prompts cover all this. Closing this issue.
