### ISSUE TITLE
CMake Error at programs/CMakeLists.txt:28 (string)

### ISSUE THREAD

**Issue by samfux84** [cryoem/eman2#401]
Hi,

I would like to report an issue regarding using CMake to build eman2.

When trying to build eman 2.3 from source (using the v2.3 release tarball from github), then I receive a CMake Error caused by programs/CMakeLists.txt

 CMake Error at programs/CMakeLists.txt:28 (string):
   string sub-command REGEX, mode REPLACE needs at least 6 arguments total to
   command.

According to

https://gitlab.kitware.com/cmake/cmake/issues/18737

this problem can be fixed by quoting the arguments of the function.

When changing programs/CMakeLists.txt:28 from

```
        string(REGEX REPLACE
                   "^.*-.*-g" ""
                   EMAN_GITHASH ${EMAN_GITHASH}
                   )
```

to

```
        string(REGEX REPLACE
                   "^.*-.*-g" ""
                   "EMAN_GITHASH" "${EMAN_GITHASH}"
                   )
```

then the error is no longer triggered

**Comment by shadowwalkersb** [comment]
`EMAN_GITHASH` is a crucial variable that contains the git hash of the commit. Unfortunately, the tarballs do not contain any git information as far as I know. So, it is not a case we want to support, but we could still set it to something to prevent the error you see. Wrapping the variables is a good idea in any case, but they shouldn't be needed for the first variable.

```
        string(REGEX REPLACE
                   "^.*-.*-g" ""
                   EMAN_GITHASH "${EMAN_GITHASH}"
                   )
```

Thanks for the suggestion!
