### ISSUE TITLE
GPU too old

### ISSUE THREAD

**Issue by chenzhao-CZ** [cryoem/eman2#457]
Hello. I have installed the binary version of EMAN2 on a rather old linux workstation and when we tried to run e2tomoseg_convnet.py we got the error of:
tensorflow.python.framework.errors_impl.InternalError: Failed to create session

i suspect that it is because the GPU is too old, because it works fine on newer workstations. And I am thinking about trying to compile EMAN2 against our GPU. However, I got stuck in the middle of compiling (even though I followed EMAN2 instructions) as I cannot let cmake recognize my conda path even though I ran cmake within conda environment.

Now at this stage, I have 3 questions:
1) Is it possible to just reconfigure GPU for the working version of EMAN2?
2) If I have to compile EMAN2 myself, how to properly configure the environment such that cmake is able to recognize miniconda?
3) How to specify GPU architecture when I compile EMAN2?

Thanks a lot for any inputs!

**Comment by sludtke42** [comment]
Hi,
recompiling EMAN2 won't make any difference. EMAN2's deep learning tools use the GPU through TensorFlow, so this is really a question of the underlying TensorFlow and CUDA installation. The specific tensorflow version should be correct, as this is provided through Anaconda in the installation, but the underlying NVidia drivers must be of a compatible version, which may restrict which GPUs will work. 

- So, what GPU do you have on the machine?
lspci |grep -i vga

- What version of the NVidia driver are you using?
modinfo nvidia|grep version

- What version of EMAN2 are you using?
e2version.py


--------------------------------------------------------------------------------------
Steven Ludtke, Ph.D. <sludtke@bcm.edu <mailto:sludtke@bcm.edu>>                      Baylor College of Medicine 
Charles C. Bell Jr., Professor of Structural Biology
Dept. of Biochemistry and Molecular Biology                      (www.bcm.edu/biochem <http://www.bcm.edu/biochem>)
Academic Director, CryoEM Core                                        (cryoem.bcm.edu <http://cryoem.bcm.edu/>)
Co-Director CIBR Center                                    (www.bcm.edu/research/cibr <http://www.bcm.edu/research/cibr>)

**Comment by chenzhao-CZ** [comment]
Hi Steve,

I am sorry that I got something else to do and dropped the ball here. Here
are the output of the commands you asked:

1. lspci | grep -i vga
02:00.0 VGA compatible controller: NVIDIA Corporation GM200 [GeForce GTX
TITAN X] (rev a1)
81:00.0 VGA compatible controller: NVIDIA Corporation GM200 [GeForce GTX
TITAN X] (rev a1)

2. modinfo nvidia | grep version
modinfo: ERROR: Module nvidia not found. (Is this the problem?)
However, nvidia-smi shows:
+------------------------------------------------------+

| NVIDIA-SMI 352.63     Driver Version: 352.63         |

|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr.
ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute
M. |
|===============================+======================+======================|
|   0  GeForce GTX TIT...  Off  | 0000:02:00.0      On |
 N/A |
| 22%   45C    P8    15W / 250W |     60MiB / 12287MiB |      0%
 Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX TIT...  Off  | 0000:81:00.0     Off |
 N/A |
| 22%   51C    P8    17W / 250W |     23MiB / 12287MiB |      0%
 Default |
+-------------------------------+----------------------+----------------------+


+-----------------------------------------------------------------------------+
| Processes:                                                       GPU
Memory |
|  GPU       PID  Type  Process name                               Usage
   |
|=============================================================================|
|    0      1859    G   /usr/bin/X
 35MiB |
+-----------------------------------------------------------------------------+

3. e2version.py
EMAN 2.31 final (GITHUB: 2019-09-30 10:41 - commit: 194df95 )
Your EMAN2 is running on:
Linux-4.2.0-38-generic-x86_64-with-debian-jessie-sid 4.2.0-38-generic
Your Python version is: 2.7.14

Do you have any suggestions based on the output above?

I appreciate your help,
Chen

**Comment by sludtke42** [comment]
If you do a 'lsmod' and nvidia isn't anywhere in the list, then yes, I would normally say that you need to install the nvidia driver. However, I am confused that you get nothing from modinfo but nvidia-smi returns something. Something funny is definitely going on with your GPU config

--------------------------------------------------------------------------------------
Steven Ludtke, Ph.D. <sludtke@bcm.edu <mailto:sludtke@bcm.edu>>                      Baylor College of Medicine 
Charles C. Bell Jr., Professor of Structural Biology
Dept. of Biochemistry and Molecular Biology                      (www.bcm.edu/biochem <http://www.bcm.edu/biochem>)
Academic Director, CryoEM Core                                        (cryoem.bcm.edu <http://cryoem.bcm.edu/>)
Co-Director CIBR Center                                    (www.bcm.edu/research/cibr <http://www.bcm.edu/research/cibr>)

**Comment by chenzhao-CZ** [comment]
Hi Steven,

Thank you for revealing the problem! I have reinstalled Nvidia driver and
it is working now. I cannot believe it was such a stupid problem...

Best,
Chen
