### ISSUE TITLE
Incorrect convolution processing under some circumstances

### ISSUE THREAD

**Issue by jcbollinger** [cryoem/eman2#460]
This is libEM/processor.cpp:13695-13697:
```
		EMData* selem = params["selem"];
		float *sd = selem->get_data();
		kernel = vector<float>(sd, sd + sizeof sd / sizeof sd[0]);
```
The intent appears to be to construct a `vector<float>` representation of the data referenced by `selem->get_data()`, but it does not actually do that.  The problem is that `sizeof sd` evaluates to the size of a pointer, probably 8 bytes on most current machines, whereas what is needed for computing the number of elements that way is the size of the whole array to which `sd` points.

It looks like changing the last of those lines to
```
		kernel = vector<float>(sd, sd + selem->get_size());
```
might produce the wanted result.

**Comment by sludtke42** [comment]
Fixed as per the author's suggestion
