### ISSUE TITLE
 No rule to make target `/usr/lib64/libGLX.so'

### ISSUE THREAD

**Issue by comrade1809** [cryoem/eman2#477]
Following the instructions at: https://blake.bcm.edu/emanwiki/EMAN2/COMPILE_EMAN2_ANACONDA
I stumbled upon this error after running the 'make' command.

`make[2]: *** No rule to make target `/usr/lib64/libGLX.so', needed by `libpyEM/libpyGLUtils2.so'.  Stop.
make[1]: *** [libpyEM/CMakeFiles/pyGLUtils2.dir/all] Error 2
make: *** [all] Error 2
`

Checking for the file, the libGLX.so does exist in the proper location. 

Any suggestions?

**Comment by sludtke42** [comment]
Nothing obvious. What do you see from 
ls -al /usr/lib64/libGLX.so

did you have the Anaconda environment activated when you ran cmake?

--------------------------------------------------------------------------------------
Steven Ludtke, Ph.D. <sludtke@bcm.edu <mailto:sludtke@bcm.edu>>                      Baylor College of Medicine 
Charles C. Bell Jr., Professor of Structural Biology
Dept. of Biochemistry and Molecular Biology                      (www.bcm.edu/biochem <http://www.bcm.edu/biochem>)
Academic Director, CryoEM Core                                        (cryoem.bcm.edu <http://cryoem.bcm.edu/>)
Co-Director CIBR Center                                    (www.bcm.edu/research/cibr <http://www.bcm.edu/research/cibr>)

**Comment by comrade1809** [comment]
Added details:
OS: CentOS Linux release 7.8.2003 (Core)

That put me on the right path.
I checked if the file was there before but not if it was a soft link. The link was pointing to a file that wasn't there.
I deleted the soft link and re-made it to the proper file: 
```
(eman2) [root@pc-lj-pb01 eman2-build]# ls -al /usr/lib64/libGL*
-------cropped-------
lrwxrwxrwx. 1 root root      15 Aug 15  2019 /usr/lib64/libGLX.so -> libGLX.so.0.0.0
-rwxr-xr-x. 1 root root   65168 Jun  5  2019 /usr/lib64/libGLX.so.0

(eman2) [root@pc-lj-pb01 eman2-build]# rm /usr/lib64/libGLX.so
rm: remove symbolic link ‘/usr/lib64/libGLX.so’? y

(eman2) [root@pc-lj-pb01 eman2-build]# ln -s /usr/lib64/libGLX.so.0 /usr/lib64/libGLX.so
```

After making the new link, the MAKE finished and MAKE INSTALL finished successfully.
I don't know why the soft link was pointing to a non-existent file.

Thanks!

**Comment by comrade1809** [comment]
Spoke too soon. Executed e2display.py after compilation and got the following error with GLX.

`[agalipch@strubio06 Topaz]$ e2display.py
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-agalipch'
failed to get the current screen resources
No XVisualInfo for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOp tion>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBuffe rSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SwapBehavior(SingleB uffer), swapInterval 1, profile  QSurfaceFormat::OpenGLContextProfile(NoProfile))
Falling back to using screens root_visual.
QXcbConnection: XCB error: 170 (Unknown), sequence: 170, resource id: 90, major code: 146 (Un known), minor code: 20
No XVisualInfo for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOp tion>(), depthBufferSize 0, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBuffer Size -1, stencilBufferSize 0, samples -1, swapBehavior QSurfaceFormat::SwapBehavior(SingleBuf fer), swapInterval -1, profile  QSurfaceFormat::OpenGLContextProfile(NoProfile))
Falling back to using screens root_visual.
Could not initialize GLX
Aborted (core dumped)
`

**Comment by sludtke42** [comment]
Can you successfully run OpenGL demos like glxgears ?

--------------------------------------------------------------------------------------
Steven Ludtke, Ph.D. <sludtke@bcm.edu <mailto:sludtke@bcm.edu>>                      Baylor College of Medicine 
Charles C. Bell Jr., Professor of Structural Biology
Dept. of Biochemistry and Molecular Biology                      (www.bcm.edu/biochem <http://www.bcm.edu/biochem>)
Academic Director, CryoEM Core                                        (cryoem.bcm.edu <http://cryoem.bcm.edu/>)
Co-Director CIBR Center                                    (www.bcm.edu/research/cibr <http://www.bcm.edu/research/cibr>)

**Comment by comrade1809** [comment]
Seems not. A black screen comes up and that's it.
I am connected to the machine via Putty with X11 enabled and Xming running.

**Comment by comrade1809** [comment]
I don't know if this will help but here is output from 'glxinfo64'


> [agalipch@strubio06 2.31]$ glxinfo64
name of display: localhost:13.0
display: localhost:13  screen: 0
direct rendering: No (If you want to find out why, try setting LIBGL_DEBUG=verbose)
server glx vendor string: SGI
server glx version string: 1.2
server glx extensions:
    GLX_ARB_multisample, GLX_EXT_import_context, GLX_EXT_visual_info,
    GLX_EXT_visual_rating, GLX_OML_swap_method, GLX_SGIS_multisample,
    GLX_SGIX_fbconfig, GLX_SGIX_hyperpipe, GLX_SGIX_swap_barrier,
    GLX_SGI_make_current_read
client glx vendor string: NVIDIA Corporation
client glx version string: 1.4
client glx extensions:
    GLX_ARB_context_flush_control, GLX_ARB_create_context,
    GLX_ARB_create_context_no_error, GLX_ARB_create_context_profile,
    GLX_ARB_create_context_robustness, GLX_ARB_fbconfig_float,
    GLX_ARB_get_proc_address, GLX_ARB_multisample, GLX_EXT_buffer_age,
    GLX_EXT_create_context_es2_profile, GLX_EXT_create_context_es_profile,
    GLX_EXT_fbconfig_packed_float, GLX_EXT_framebuffer_sRGB,
    GLX_EXT_import_context, GLX_EXT_stereo_tree, GLX_EXT_swap_control,
    GLX_EXT_swap_control_tear, GLX_EXT_texture_from_pixmap,
    GLX_EXT_visual_info, GLX_EXT_visual_rating, GLX_NV_copy_buffer,
    GLX_NV_copy_image, GLX_NV_delay_before_swap, GLX_NV_float_buffer,
    GLX_NV_multigpu_context, GLX_NV_multisample_coverage,
    GLX_NV_robustness_video_memory_purge, GLX_NV_swap_group,
    GLX_SGIX_fbconfig, GLX_SGIX_pbuffer, GLX_SGI_swap_control,
    GLX_SGI_video_sync
GLX version: 1.2
GLX extensions:
    GLX_ARB_get_proc_address, GLX_ARB_multisample, GLX_EXT_import_context,
    GLX_EXT_visual_info, GLX_EXT_visual_rating, GLX_SGIX_fbconfig
OpenGL vendor string: Microsoft Corporation
OpenGL renderer string: GDI Generic
OpenGL version string: 1.1.0
OpenGL extensions:
    GL_EXT_bgra

32 GLX Visuals
    visual  x   bf lv rg d st  colorbuffer  sr ax dp st accumbuffer  ms  cav
  id dep cl sp  sz l  ci b ro  r  g  b  a F gb bf th cl  r  g  b  a ns b eat
----------------------------------------------------------------------------
0x022 24 tc  1  24  0 r  . .   8  8  8  0 .  .  0  0  0  0  0  0  0 2059021784 0 None
0x023 24 tc  1  24  0 r  . .   8  8  8  0 .  .  0  0  0 16 16 16 16  0 0 None
0x024 24 tc  1  24  0 r  . .   8  8  8  0 .  .  0  0  8  0  0  0  0  0 0 None
0x025 24 tc  1  24  0 r  . .   8  8  8  0 .  .  0  0  8 16 16 16 16  0 0 None
0x026 24 tc  1  24  0 r  y .   8  8  8  0 .  .  0  0  0  0  0  0  0 128 0 None
0x027 24 tc  1  24  0 r  y .   8  8  8  0 .  .  0  0  0 16 16 16 16  0 0 None
0x028 24 tc  1  24  0 r  y .   8  8  8  0 .  .  0  0  8  0  0  0  0 20896 0 None
0x029 24 tc  1  24  0 r  y .   8  8  8  0 .  .  0  0  8 16 16 16 16  6 1 None
0x02a 24 tc  1  24  0 r  . .   8  8  8  0 .  .  2  0  0  0  0  0  0  7 0 None
0x02b 24 tc  1  24  0 r  . .   8  8  8  0 .  .  2  0  0 16 16 16 16  0 0 None
0x02c 24 tc  1  24  0 r  . .   8  8  8  0 .  .  2  0  8  0  0  0  0  8 0 None
0x02d 24 tc  1  24  0 r  . .   8  8  8  0 .  .  2  0  8 16 16 16 16  0 0 None
0x02e 24 tc  1  24  0 r  y .   8  8  8  0 .  .  2  0  0  0  0  0  0  8 0 None
0x02f 24 tc  1  24  0 r  y .   8  8  8  0 .  .  2  0  0 16 16 16 16 1052032 0 None
0x030 24 tc  1  24  0 r  y .   8  8  8  0 .  .  2  0  8  0  0  0  0 3149824 0 None
0x031 24 tc  1  24  0 r  y .   8  8  8  0 .  .  2  0  8 16 16 16 16  3 8 None
0x032 24 tc  1  24  0 r  . .   8  8  8  0 .  .  0 24  0  0  0  0  0 244 0 None
0x033 24 tc  1  24  0 r  . .   8  8  8  0 .  .  0 24  0 16 16 16 16 24 0 None
0x034 24 tc  1  24  0 r  . .   8  8  8  0 .  .  0 24  8  0  0  0  0  4 0 None
0x035 24 tc  1  24  0 r  . .   8  8  8  0 .  .  0 24  8 16 16 16 16 8964784 0 None
0x036 24 tc  1  24  0 r  y .   8  8  8  0 .  .  0 24  0  0  0  0  0  0 0 None
0x037 24 tc  1  24  0 r  y .   8  8  8  0 .  .  0 24  0 16 16 16 16  0 0 None
0x038 24 tc  1  24  0 r  y .   8  8  8  0 .  .  0 24  8  0  0  0  0  0 0 None
0x039 24 tc  1  24  0 r  y .   8  8  8  0 .  .  0 24  8 16 16 16 16  0 0 None
0x03a 24 tc  1  24  0 r  . .   8  8  8  0 .  .  2 24  0  0  0  0  0  0 0 None
0x03b 24 tc  1  24  0 r  . .   8  8  8  0 .  .  2 24  0 16 16 16 16  0 0 None
0x03c 24 tc  1  24  0 r  . .   8  8  8  0 .  .  2 24  8  0  0  0  0  0 0 None
0x03d 24 tc  1  24  0 r  . .   8  8  8  0 .  .  2 24  8 16 16 16 16  0 0 None
0x03e 24 tc  1  24  0 r  y .   8  8  8  0 .  .  2 24  0  0  0  0  0  0 0 None
0x03f 24 tc  1  24  0 r  y .   8  8  8  0 .  .  2 24  0 16 16 16 16  0 0 None
0x040 24 tc  1  24  0 r  y .   8  8  8  0 .  .  2 24  8  0  0  0  0  0 0 None
0x041 24 tc  1  24  0 r  y .   8  8  8  0 .  .  2 24  8 16 16 16 16  0 0 None

32 GLXFBConfigs:
    visual  x   bf lv rg d st  colorbuffer  sr ax dp st accumbuffer  ms  cav
  id dep cl sp  sz l  ci b ro  r  g  b  a F gb bf th cl  r  g  b  a ns b eat
----------------------------------------------------------------------------
0x022 24 tc  1  24  0    . .   8  8  8  0 .  .  0  0  0  0  0  0  0  0 0 None
0x023 24 tc  1  24  0    . .   8  8  8  0 .  .  0  0  0 16 16 16 16  0 0 None
0x024 24 tc  1  24  0    . .   8  8  8  0 .  .  0  0  8  0  0  0  0  0 0 None
0x025 24 tc  1  24  0    . .   8  8  8  0 .  .  0  0  8 16 16 16 16  0 0 None
0x026 24 tc  1  24  0    y .   8  8  8  0 .  .  0  0  0  0  0  0  0  0 0 None
0x027 24 tc  1  24  0    y .   8  8  8  0 .  .  0  0  0 16 16 16 16  0 0 None
0x028 24 tc  1  24  0    y .   8  8  8  0 .  .  0  0  8  0  0  0  0  0 0 None
0x029 24 tc  1  24  0    y .   8  8  8  0 .  .  0  0  8 16 16 16 16  0 0 None
0x02a 24 tc  1  24  0    . .   8  8  8  0 .  .  2  0  0  0  0  0  0  0 0 None
0x02b 24 tc  1  24  0    . .   8  8  8  0 .  .  2  0  0 16 16 16 16  0 0 None
0x02c 24 tc  1  24  0    . .   8  8  8  0 .  .  2  0  8  0  0  0  0  0 0 None
0x02d 24 tc  1  24  0    . .   8  8  8  0 .  .  2  0  8 16 16 16 16  0 0 None
0x02e 24 tc  1  24  0    y .   8  8  8  0 .  .  2  0  0  0  0  0  0  0 0 None
0x02f 24 tc  1  24  0    y .   8  8  8  0 .  .  2  0  0 16 16 16 16  0 0 None
0x030 24 tc  1  24  0    y .   8  8  8  0 .  .  2  0  8  0  0  0  0  0 0 None
0x031 24 tc  1  24  0    y .   8  8  8  0 .  .  2  0  8 16 16 16 16  0 0 None
0x032 24 tc  1  24  0    . .   8  8  8  0 .  .  0 24  0  0  0  0  0  0 0 None
0x033 24 tc  1  24  0    . .   8  8  8  0 .  .  0 24  0 16 16 16 16  0 0 None
0x034 24 tc  1  24  0    . .   8  8  8  0 .  .  0 24  8  0  0  0  0  0 0 None
0x035 24 tc  1  24  0    . .   8  8  8  0 .  .  0 24  8 16 16 16 16  0 0 None
0x036 24 tc  1  24  0    y .   8  8  8  0 .  .  0 24  0  0  0  0  0  0 0 None
0x037 24 tc  1  24  0    y .   8  8  8  0 .  .  0 24  0 16 16 16 16  0 0 None
0x038 24 tc  1  24  0    y .   8  8  8  0 .  .  0 24  8  0  0  0  0  0 0 None
0x039 24 tc  1  24  0    y .   8  8  8  0 .  .  0 24  8 16 16 16 16  0 0 None
0x03a 24 tc  1  24  0    . .   8  8  8  0 .  .  2 24  0  0  0  0  0  0 0 None
0x03b 24 tc  1  24  0    . .   8  8  8  0 .  .  2 24  0 16 16 16 16  0 0 None
0x03c 24 tc  1  24  0    . .   8  8  8  0 .  .  2 24  8  0  0  0  0  0 0 None
0x03d 24 tc  1  24  0    . .   8  8  8  0 .  .  2 24  8 16 16 16 16  0 0 None
0x03e 24 tc  1  24  0    y .   8  8  8  0 .  .  2 24  0  0  0  0  0  0 0 None
0x03f 24 tc  1  24  0    y .   8  8  8  0 .  .  2 24  0 16 16 16 16  0 0 None
0x040 24 tc  1  24  0    y .   8  8  8  0 .  .  2 24  8  0  0  0  0  0 0 None
0x041 24 tc  1  24  0    y .   8  8  8  0 .  .  2 24  8 16 16 16 16  0 0 None

**Comment by sludtke42** [comment]
Remote OpenGL isn't equivalent to remote X sessions. Some remote session setups permit OpenGL and others do not. See this page:
http://eman2.org/Remote



--------------------------------------------------------------------------------------
Steven Ludtke, Ph.D. <sludtke@bcm.edu <mailto:sludtke@bcm.edu>>                      Baylor College of Medicine 
Charles C. Bell Jr., Professor of Structural Biology
Dept. of Biochemistry and Molecular Biology                      (www.bcm.edu/biochem <http://www.bcm.edu/biochem>)
Academic Director, CryoEM Core                                        (cryoem.bcm.edu <http://cryoem.bcm.edu/>)
Co-Director CIBR Center                                    (www.bcm.edu/research/cibr <http://www.bcm.edu/research/cibr>)

**Comment by comrade1809** [comment]
Unfortunately one of the options, rsync, assumes that the cluster and local machine are both Linux. I am building the app for Windows users that access our Linux cluster via ssh.

Attempted to access the application through NoMachine but received the error:

```
e2display.py
Traceback (most recent call last):
  File "/apps/GNU/eman2/2.31/bin/e2display.py", line 36, in <module>
    from eman2_gui.emapplication import EMApp
  File "/apps/GNU/eman2/2.31/lib/python3.7/site-packages/eman2_gui/emapplication.py", line 40, in <module>
    from libpyGLUtils2 import *
ImportError: libOpenGL.so.0: cannot open shared object file: No such file or directory
```

**Comment by sludtke42** [comment]
Hi,

Ok, since this is continuing, I'd like to point out that we don't really do support via Github normally. There are two Google groups where all of the historical discussions on these topics are archived:
http://groups.google.com/group/eman2
http://groups.google.com/group/eman2-developers

The rsync approach is for users who can use a hybrid approach where they do preprocessing on a local machine, and only large processing runs on the cluster.  It isn't right for every situation, but many sysadmins do not like GUIs to be run on the cluster, as they are often resource intensive on the head-node.

We used NoMachine for a while a decade ago, but their OpenGL support became pretty much permanently broken as far as I could tell at the time. I can't tell you whether it works or not now. 

The problem you need to solve here isn't an EMAN issue, it's a remote Linux GUI access issue. If you plan to run EMAN2 GUI programs directly on the cluster, then you need a remote solution which provides X11 and (non-buggy) OpenGL. There are several solutions, particularly for Windows, which claim to support OpenGL, but don't do it completely.  The only solution I know personally works well (I have used it every single day for the last 4 months) is TurboVNC/VirtualGL solution as described on the EMAN wiki. There ARE people who have made other solutions work, but not in a reliably reproducible way, so we don't have any documentation on them.

--------------------------------------------------------------------------------------
Steven Ludtke, Ph.D. <sludtke@bcm.edu <mailto:sludtke@bcm.edu>>                      Baylor College of Medicine 
Charles C. Bell Jr., Professor of Structural Biology
Dept. of Biochemistry and Molecular Biology                      (www.bcm.edu/biochem <http://www.bcm.edu/biochem>)
Academic Director, CryoEM Core                                        (cryoem.bcm.edu <http://cryoem.bcm.edu/>)
Co-Director CIBR Center                                    (www.bcm.edu/research/cibr <http://www.bcm.edu/research/cibr>)

**Comment by comrade1809** [comment]
Okay, thank you. I will take a look at implementing TurboVNC.

**Comment by comrade1809** [comment]
This can be closed, I've opened an issue in google/groups.
https://groups.google.com/forum/#!topic/eman2/jeJIgdeXSk0
