### ISSUE TITLE
New release supporting recent boost.python

### ISSUE THREAD

**Issue by ccoulombe** [cryoem/eman2#498]
Any tagged release supporting boost 1.65+ coming soon? The old API of `boost::python::numeric`...is well, old.

Thanks!

**Comment by sludtke42** [comment]
The current snapshot versions are Python 3 and use Boost 1.69. All of these things will transition at the same time with the next release. We were hoping for the end of the month, but we have to coordinate among several groups for a release, so I suspect a few more delays are inevitable.  

The snapshot (and current version on GitHub) are both quite stable at this point. Every so often we find a small bug, but everyone in my group is using the current pre-release on a day to day basis. I'll also point out that compiling from source is now only very slightly more difficult than installing the binary (except on windows). The instructions for setting up a build from source are quite straightforward to follow (but should be followed exactly).
