### ISSUE TITLE
How to determine pixel width (Angstrom) when calculating FSC using e2proc3d?

### ISSUE THREAD

**Issue by ZhidongYang** [cryoem/eman2#512]
The caculation of FSC between two tomograms should determine pixel width, but no such parameters can be found in e2proc3d.py? Is there any solution?

**Comment by sludtke42** [comment]
I'm not sure I understand the question. Pixel size (A/pix) is stored in the header of most image formats (including HDF). You should normally try to make sure this value is correct. If you used EMAN to reconstruct tomograms, and A/pix is not correctly set in the header, then you didn't follow the process properly, as CTF determination cannot work properly without this value.

To look at the header of an image/volume

e2iminfo.py -H <image>
or
e2display.py
press 'Info'
single click (select) an image file, and look for apix_x in the info panel

You can force A/pix to a specific value with e2proc3d.py using the --apix option, but if you need to do this you might first wish to figure out why it was necessary.

**Comment by ZhidongYang** [comment]
Thanks a lot for your help, I got the solution to my problem.










At 2020-11-08 21:54:13, "Steve Ludtke" <notifications@github.com> wrote:

I'm not sure I understand the question. Pixel size (A/pix) is stored in the header of most image formats (including HDF). You should normally try to make sure this value is correct. If you used EMAN to reconstruct tomograms, and A/pix is not correctly set in the header, then you didn't follow the process properly, as CTF determination cannot work properly without this value.

To look at the header of an image/volume

e2iminfo.py -H <image>
or
e2display.py
press 'Info'
single click (select) an image file, and look for apix_x in the info panel

You can force A/pix to a specific value with e2proc3d.py using the --apix option, but if you need to do this you might first wish to figure out why it was necessary.
